/**
 * theme.config.js
 * Vocabulary pools for each theme.
 * Each theme has ~30 words per level: easy, medium, hard.
 * Each word contains:
 *   en – English word
 *   vi – Vietnamese translation
 */

module.exports = {
  fairytale: {
    easy: [
      { en: "castle", vi: "lâu đài" },
      { en: "princess", vi: "công chúa" },
      { en: "king", vi: "nhà vua" },
      { en: "queen", vi: "hoàng hậu" },
      { en: "dragon", vi: "rồng" },
      { en: "magic", vi: "phép thuật" },
      { en: "wand", vi: "đũa phép" },
      { en: "crown", vi: "vương miện" },
      { en: "knight", vi: "hiệp sĩ" },
      { en: "fairy", vi: "tiên nữ" },
      { en: "prince", vi: "hoàng tử" },
      { en: "giant", vi: "người khổng lồ" },
      { en: "witch", vi: "phù thủy" },
      { en: "hero", vi: "anh hùng" },
      { en: "apple", vi: "quả táo" },
      { en: "forest", vi: "khu rừng" },
      { en: "tower", vi: "tháp" },
      { en: "gold", vi: "vàng" },
      { en: "ball", vi: "vũ hội" },
      { en: "dance", vi: "nhảy múa" },
      { en: "rose", vi: "hoa hồng" },
      { en: "glass", vi: "thủy tinh" },
      { en: "shoe", vi: "giày" },
      { en: "frog", vi: "ếch" },
      { en: "wish", vi: "ước mơ" },
      { en: "ring", vi: "nhẫn" },
      { en: "light", vi: "ánh sáng" },
      { en: "star", vi: "ngôi sao" },
      { en: "dream", vi: "giấc mơ" },
      { en: "cloud", vi: "đám mây" }
    ],
    medium: [
      { en: "enchanted", vi: "bị mê hoặc" },
      { en: "mystical", vi: "huyền bí" },
      { en: "sorcerer", vi: "pháp sư" },
      { en: "spell", vi: "bùa chú" },
      { en: "carriage", vi: "cỗ xe" },
      { en: "pumpkin", vi: "quả bí ngô" },
      { en: "banquet", vi: "yến tiệc" },
      { en: "treasure", vi: "kho báu" },
      { en: "curse", vi: "lời nguyền" },
      { en: "fortune", vi: "vận may" },
      { en: "mirror", vi: "gương" },
      { en: "disguise", vi: "cải trang" },
      { en: "bravery", vi: "lòng dũng cảm" },
      { en: "destiny", vi: "định mệnh" },
      { en: "hidden", vi: "ẩn giấu" },
      { en: "ancient", vi: "cổ xưa" },
      { en: "mysterious", vi: "bí ẩn" },
      { en: "prophecy", vi: "lời tiên tri" },
      { en: "legend", vi: "huyền thoại" },
      { en: "royal", vi: "hoàng gia" },
      { en: "scepter", vi: "vương trượng" },
      { en: "guardian", vi: "người bảo vệ" },
      { en: "alchemy", vi: "thuật giả kim" },
      { en: "adventure", vi: "cuộc phiêu lưu" },
      { en: "riddle", vi: "câu đố" },
      { en: "gateway", vi: "cổng" },
      { en: "phoenix", vi: "phượng hoàng" },
      { en: "grace", vi: "duyên dáng" },
      { en: "ballroom", vi: "phòng khiêu vũ" },
      { en: "illumination", vi: "ánh sáng rực rỡ" }
    ],
    hard: [
      { en: "chivalry", vi: "tinh thần hiệp sĩ" },
      { en: "transformation", vi: "sự biến đổi" },
      { en: "bewilderment", vi: "sự bối rối" },
      { en: "incantation", vi: "thần chú" },
      { en: "labyrinth", vi: "mê cung" },
      { en: "benevolent", vi: "nhân từ" },
      { en: "ominous", vi: "điềm xấu" },
      { en: "metamorphosis", vi: "sự lột xác" },
      { en: "luminescent", vi: "phát quang" },
      { en: "enchantment", vi: "sự mê hoặc" },
      { en: "apparition", vi: "bóng ma" },
      { en: "mythical", vi: "huyền thoại" },
      { en: "perpetual", vi: "vĩnh cửu" },
      { en: "reverence", vi: "sự tôn kính" },
      { en: "celestial", vi: "thiên thể" },
      { en: "resplendent", vi: "rực rỡ" },
      { en: "sanctuary", vi: "thánh địa" },
      { en: "phantasm", vi: "ảo ảnh" },
      { en: "fascination", vi: "sự mê hoặc" },
      { en: "ephemeral", vi: "chóng tàn" },
      { en: "quintessence", vi: "tinh hoa" },
      { en: "serendipity", vi: "sự tình cờ may mắn" },
      { en: "ethereal", vi: "thoát tục" },
      { en: "grandiose", vi: "hoành tráng" },
      { en: "magnanimous", vi: "hào hiệp" },
      { en: "miraculous", vi: "kỳ diệu" },
      { en: "phantom", vi: "bóng ma" },
      { en: "fable", vi: "truyện ngụ ngôn" },
      { en: "whimsical", vi: "kỳ quái" },
      { en: "empyrean", vi: "thiên đường" }
    ]
  },

  /* --------------------
     Repeat same pattern
     for adventure, animal,
     science, nature, music…
     -------------------- */

  // ... (For brevity not all themes are expanded here,
  //      but each word follows the same { en, vi } structure.)
  nature: {
    easy: [
      { en: "tree", vi: "cây" },
      { en: "flower", vi: "hoa" },
      { en: "river", vi: "sông" },
      { en: "mountain", vi: "núi" },
      { en: "sky", vi: "bầu trời" },
      { en: "sun", vi: "mặt trời" },
      { en: "moon", vi: "mặt trăng" },
      { en: "rain", vi: "mưa" },
      { en: "snow", vi: "tuyết" },
      { en: "wind", vi: "gió" },
      { en: "cloud", vi: "mây" },
      { en: "leaf", vi: "lá" },
      { en: "rock", vi: "đá" },
      { en: "grass", vi: "cỏ" },
      { en: "sand", vi: "cát" },
      { en: "beach", vi: "bãi biển" },
      { en: "lake", vi: "hồ" },
      { en: "ocean", vi: "đại dương" },
      { en: "forest", vi: "rừng" },
      { en: "bird", vi: "chim" },
      { en: "bee", vi: "ong" },
      { en: "butterfly", vi: "bướm" },
      { en: "rose", vi: "hoa hồng" },
      { en: "daisy", vi: "cúc" },
      { en: "pine", vi: "thông" },
      { en: "apple", vi: "táo" },
      { en: "mango", vi: "xoài" },
      { en: "seed", vi: "hạt" },
      { en: "root", vi: "rễ" },
      { en: "branch", vi: "cành" }
    ],
    medium: [
      { en: "meadow", vi: "đồng cỏ" },
      { en: "valley", vi: "thung lũng" },
      { en: "canyon", vi: "hẻm núi" },
      { en: "glacier", vi: "sông băng" },
      { en: "tundra", vi: "đồng hoang băng giá" },
      { en: "savanna", vi: "thảo nguyên" },
      { en: "desert", vi: "sa mạc" },
      { en: "volcano", vi: "núi lửa" },
      { en: "earthquake", vi: "động đất" },
      { en: "hurricane", vi: "bão lớn" },
      { en: "monsoon", vi: "gió mùa" },
      { en: "ecosystem", vi: "hệ sinh thái" },
      { en: "habitat", vi: "môi trường sống" },
      { en: "biodiversity", vi: "đa dạng sinh học" },
      { en: "climate", vi: "khí hậu" },
      { en: "pollination", vi: "thụ phấn" },
      { en: "migration", vi: "di cư" },
      { en: "photosynthesis", vi: "quang hợp" },
      { en: "sediment", vi: "trầm tích" },
      { en: "erosion", vi: "xói mòn" },
      { en: "geology", vi: "địa chất" },
      { en: "flora", vi: "thực vật" },
      { en: "fauna", vi: "động vật" },
      { en: "wetlands", vi: "đầm lầy" },
      { en: "reef", vi: "rạn san hô" },
      { en: "canopy", vi: "tán rừng" },
      { en: "soil", vi: "đất" },
      { en: "compost", vi: "phân hữu cơ" },
      { en: "rainforest", vi: "rừng mưa nhiệt đới" },
      { en: "permafrost", vi: "tầng đất đóng băng vĩnh cửu" }
    ],
    hard: [
      { en: "sustainability", vi: "bền vững" },
      { en: "biogeochemistry", vi: "địa hóa sinh học" },
      { en: "paleontology", vi: "cổ sinh học" },
      { en: "hydrosphere", vi: "thủy quyển" },
      { en: "biosphere", vi: "sinh quyển" },
      { en: "atmosphere", vi: "khí quyển" },
      { en: "cryosphere", vi: "băng quyển" },
      { en: "geomorphology", vi: "địa mạo học" },
      { en: "pedology", vi: "thổ nhưỡng học" },
      { en: "ecophysiology", vi: "sinh lý học sinh thái" },
      { en: "photosynthetic", vi: "thuộc quang hợp" },
      { en: "stratosphere", vi: "tầng bình lưu" },
      { en: "troposphere", vi: "tầng đối lưu" },
      { en: "lithosphere", vi: "thạch quyển" },
      { en: "ecotone", vi: "vùng chuyển tiếp sinh thái" },
      { en: "succession", vi: "diễn thế sinh thái" },
      { en: "permaculture", vi: "nông nghiệp bền vững" },
      { en: "conservation", vi: "bảo tồn" },
      { en: "bioresilience", vi: "khả năng phục hồi sinh học" },
      { en: "anthropogenic", vi: "do con người gây ra" },
      { en: "biomagnification", vi: "khuếch đại sinh học" },
      { en: "symbiosis", vi: "cộng sinh" },
      { en: "mutualism", vi: "cộng sinh đôi bên cùng lợi" },
      { en: "commensalism", vi: "cộng sinh một bên có lợi" },
      { en: "endemic", vi: "đặc hữu" },
      { en: "xerophyte", vi: "cây chịu hạn" },
      { en: "halophyte", vi: "cây chịu mặn" },
      { en: "bioclimatic", vi: "sinh khí hậu" },
      { en: "orogeny", vi: "quá trình tạo núi" },
      { en: "albedo", vi: "suất phản chiếu" }
    ]
  },

  music: {
    easy: [
      { en: "song", vi: "bài hát" },
      { en: "note", vi: "nốt nhạc" },
      { en: "beat", vi: "nhịp" },
      { en: "drum", vi: "trống" },
      { en: "guitar", vi: "đàn guitar" },
      { en: "piano", vi: "đàn piano" },
      { en: "violin", vi: "đàn violin" },
      { en: "flute", vi: "sáo" },
      { en: "dance", vi: "nhảy múa" },
      { en: "sing", vi: "hát" },
      { en: "voice", vi: "giọng hát" },
      { en: "melody", vi: "giai điệu" },
      { en: "rhythm", vi: "nhịp điệu" },
      { en: "band", vi: "ban nhạc" },
      { en: "choir", vi: "dàn hợp xướng" },
      { en: "sound", vi: "âm thanh" },
      { en: "clap", vi: "vỗ tay" },
      { en: "listen", vi: "lắng nghe" },
      { en: "play", vi: "chơi (nhạc cụ)" },
      { en: "tune", vi: "giai điệu" },
      { en: "horn", vi: "kèn" },
      { en: "bell", vi: "chuông" },
      { en: "lyric", vi: "lời bài hát" },
      { en: "duet", vi: "song ca" },
      { en: "solo", vi: "độc tấu" },
      { en: "trio", vi: "bộ ba" },
      { en: "quartet", vi: "bộ tứ" },
      { en: "music", vi: "âm nhạc" },
      { en: "bass", vi: "âm trầm" },
      { en: "harmony", vi: "hòa âm" }
    ],
    medium: [
      { en: "symphony", vi: "bản giao hưởng" },
      { en: "orchestra", vi: "dàn nhạc" },
      { en: "composer", vi: "nhà soạn nhạc" },
      { en: "conductor", vi: "nhạc trưởng" },
      { en: "arrangement", vi: "phối khí" },
      { en: "improvisation", vi: "ngẫu hứng" },
      { en: "tempo", vi: "nhịp độ" },
      { en: "crescendo", vi: "cao trào" },
      { en: "decrescendo", vi: "giảm dần" },
      { en: "pitch", vi: "cao độ" },
      { en: "scale", vi: "thang âm" },
      { en: "octave", vi: "quãng tám" },
      { en: "chord", vi: "hợp âm" },
      { en: "key", vi: "giọng (nhạc)" },
      { en: "minor", vi: "thứ (giọng)" },
      { en: "major", vi: "trưởng (giọng)" },
      { en: "melodic", vi: "du dương" },
      { en: "harmonic", vi: "hài hòa" },
      { en: "notation", vi: "kí hiệu âm nhạc" },
      { en: "acoustic", vi: "âm học" },
      { en: "vibrato", vi: "rung âm" },
      { en: "syncopation", vi: "ngắt nhịp" },
      { en: "ensemble", vi: "nhóm biểu diễn" },
      { en: "aria", vi: "aria (đơn ca)" },
      { en: "ballad", vi: "ballad" },
      { en: "cantata", vi: "cantata" },
      { en: "sonata", vi: "sonata" },
      { en: "concerto", vi: "concerto" },
      { en: "polyphony", vi: "đa âm" },
      { en: "counterpoint", vi: "đối âm" }
    ],
    hard: [
      { en: "ethnomusicology", vi: "dân tộc nhạc học" },
      { en: "counterpointal", vi: "thuộc đối âm" },
      { en: "polyphonic", vi: "đa âm" },
      { en: "microtonality", vi: "vi cung" },
      { en: "atonality", vi: "phi điệu tính" },
      { en: "serialism", vi: "chủ nghĩa chuỗi" },
      { en: "chromaticism", vi: "sử dụng nốt biến âm" },
      { en: "modulation", vi: "chuyển giọng" },
      { en: "dissonance", vi: "nghịch âm" },
      { en: "consonance", vi: "thuận âm" },
      { en: "glissando", vi: "lướt nốt" },
      { en: "sforzando", vi: "nhấn mạnh đột ngột" },
      { en: "tessitura", vi: "cao độ chủ yếu" },
      { en: "orchestration", vi: "phối dàn nhạc" },
      { en: "transposition", vi: "chuyển cung" },
      { en: "improvisational", vi: "ngẫu hứng" },
      { en: "synaesthesia", vi: "liên giác quan" },
      { en: "virtuosity", vi: "kỹ thuật điêu luyện" },
      { en: "contrapuntal", vi: "thuộc đối âm" },
      { en: "ostinato", vi: "mô-típ lặp lại" },
      { en: "heterophony", vi: "đa âm khác bè" },
      { en: "homophony", vi: "đồng âm" },
      { en: "aleatoric", vi: "ngẫu hứng ngẫu nhiên" },
      { en: "rubato", vi: "lấy nhịp tự do" },
      { en: "legato", vi: "liền tiếng" },
      { en: "staccato", vi: "ngắt tiếng" },
      { en: "pizzicato", vi: "gảy dây" },
      { en: "timbre", vi: "âm sắc" },
      { en: "harmonics", vi: "hòa âm bội" },
      { en: "appoggiatura", vi: "nốt dựa" }
    ]
  },
  animal: {
    easy: [
      { en: "cat", vi: "mèo" },
      { en: "dog", vi: "chó" },
      { en: "bird", vi: "chim" },
      { en: "fish", vi: "cá" },
      { en: "lion", vi: "sư tử" },
      { en: "tiger", vi: "hổ" },
      { en: "bear", vi: "gấu" },
      { en: "mouse", vi: "chuột" },
      { en: "cow", vi: "bò" },
      { en: "horse", vi: "ngựa" },
      { en: "sheep", vi: "cừu" },
      { en: "duck", vi: "vịt" },
      { en: "goat", vi: "dê" },
      { en: "pig", vi: "heo" },
      { en: "rabbit", vi: "thỏ" },
      { en: "fox", vi: "cáo" },
      { en: "wolf", vi: "sói" },
      { en: "deer", vi: "nai" },
      { en: "bee", vi: "ong" },
      { en: "ant", vi: "kiến" },
      { en: "frog", vi: "ếch" },
      { en: "snake", vi: "rắn" },
      { en: "elephant", vi: "voi" },
      { en: "giraffe", vi: "hươu cao cổ" },
      { en: "monkey", vi: "khỉ" },
      { en: "zebra", vi: "ngựa vằn" },
      { en: "whale", vi: "cá voi" },
      { en: "shark", vi: "cá mập" },
      { en: "dolphin", vi: "cá heo" },
      { en: "panda", vi: "gấu trúc" }
    ],
    medium: [
      { en: "falcon", vi: "chim ưng" },
      { en: "panther", vi: "báo đen" },
      { en: "crocodile", vi: "cá sấu" },
      { en: "hyena", vi: "linh cẩu" },
      { en: "leopard", vi: "báo" },
      { en: "ostrich", vi: "đà điểu" },
      { en: "pelican", vi: "bồ nông" },
      { en: "reptile", vi: "bò sát" },
      { en: "amphibian", vi: "lưỡng cư" },
      { en: "marsupial", vi: "thú có túi" },
      { en: "insect", vi: "côn trùng" },
      { en: "herbivore", vi: "động vật ăn cỏ" },
      { en: "carnivore", vi: "động vật ăn thịt" },
      { en: "omnivore", vi: "động vật ăn tạp" },
      { en: "predator", vi: "động vật săn mồi" },
      { en: "nocturnal", vi: "hoạt động về đêm" },
      { en: "migration", vi: "di cư" },
      { en: "camouflage", vi: "ngụy trang" },
      { en: "habitat", vi: "môi trường sống" },
      { en: "ecosystem", vi: "hệ sinh thái" },
      { en: "species", vi: "loài" },
      { en: "mammal", vi: "động vật có vú" },
      { en: "arachnid", vi: "lớp nhện" },
      { en: "mollusk", vi: "thân mềm" },
      { en: "cephalopod", vi: "chân đầu" },
      { en: "aviary", vi: "chuồng chim" },
      { en: "colony", vi: "đàn" },
      { en: "pack", vi: "bầy" },
      { en: "herd", vi: "đàn thú" },
      { en: "primate", vi: "linh trưởng" }
    ],
    hard: [
      { en: "echolocation", vi: "định vị bằng tiếng vang" },
      { en: "photosynthesis", vi: "quang hợp" },
      { en: "metamorphosis", vi: "biến thái" },
      { en: "symbiosis", vi: "cộng sinh" },
      { en: "hibernation", vi: "ngủ đông" },
      { en: "carapace", vi: "mai" },
      { en: "endangered", vi: "đang bị đe dọa" },
      { en: "conservation", vi: "bảo tồn" },
      { en: "evolution", vi: "tiến hóa" },
      { en: "biodiversity", vi: "đa dạng sinh học" },
      { en: "taxonomy", vi: "phân loại học" },
      { en: "phylum", vi: "ngành (sinh học)" },
      { en: "genus", vi: "chi (sinh học)" },
      { en: "arachnology", vi: "nghiên cứu nhện" },
      { en: "ornithology", vi: "nghiên cứu chim" },
      { en: "ichthyology", vi: "nghiên cứu cá" },
      { en: "herpetology", vi: "nghiên cứu bò sát" },
      { en: "paleontology", vi: "cổ sinh học" },
      { en: "morphology", vi: "hình thái học" },
      { en: "predation", vi: "săn mồi" },
      { en: "respiration", vi: "hô hấp" },
      { en: "amniote", vi: "động vật màng ối" },
      { en: "vertebrate", vi: "động vật có xương sống" },
      { en: "invertebrate", vi: "động vật không xương sống" },
      { en: "bioluminescence", vi: "sinh học phát quang" },
      { en: "noctilucent", vi: "phát sáng ban đêm" },
      { en: "saprophytic", vi: "hoại sinh" },
      { en: "endothermic", vi: "máu nóng" },
      { en: "ectothermic", vi: "máu lạnh" },
      { en: "hydrodynamic", vi: "thủy động lực học" }
    ]
  },

  science: {
    easy: [
      { en: "atom", vi: "nguyên tử" },
      { en: "cell", vi: "tế bào" },
      { en: "star", vi: "ngôi sao" },
      { en: "sun", vi: "mặt trời" },
      { en: "moon", vi: "mặt trăng" },
      { en: "light", vi: "ánh sáng" },
      { en: "heat", vi: "nhiệt" },
      { en: "rock", vi: "đá" },
      { en: "water", vi: "nước" },
      { en: "air", vi: "không khí" },
      { en: "plant", vi: "thực vật" },
      { en: "animal", vi: "động vật" },
      { en: "earth", vi: "trái đất" },
      { en: "space", vi: "vũ trụ" },
      { en: "robot", vi: "người máy" },
      { en: "lab", vi: "phòng thí nghiệm" },
      { en: "test", vi: "thử nghiệm" },
      { en: "energy", vi: "năng lượng" },
      { en: "sound", vi: "âm thanh" },
      { en: "force", vi: "lực" },
      { en: "magnet", vi: "nam châm" },
      { en: "metal", vi: "kim loại" },
      { en: "planet", vi: "hành tinh" },
      { en: "rocket", vi: "tên lửa" },
      { en: "cloud", vi: "đám mây" },
      { en: "rain", vi: "mưa" },
      { en: "snow", vi: "tuyết" },
      { en: "wind", vi: "gió" },
      { en: "code", vi: "mã" },
      { en: "math", vi: "toán" }
    ],
    medium: [
      { en: "gravity", vi: "trọng lực" },
      { en: "friction", vi: "ma sát" },
      { en: "photosynthesis", vi: "quang hợp" },
      { en: "evaporation", vi: "bay hơi" },
      { en: "condensation", vi: "ngưng tụ" },
      { en: "electricity", vi: "điện" },
      { en: "circuit", vi: "mạch điện" },
      { en: "voltage", vi: "điện áp" },
      { en: "current", vi: "dòng điện" },
      { en: "molecule", vi: "phân tử" },
      { en: "organism", vi: "sinh vật" },
      { en: "protein", vi: "chất đạm" },
      { en: "virus", vi: "vi-rút" },
      { en: "bacteria", vi: "vi khuẩn" },
      { en: "galaxy", vi: "thiên hà" },
      { en: "asteroid", vi: "tiểu hành tinh" },
      { en: "neutron", vi: "nơtron" },
      { en: "proton", vi: "prôtôn" },
      { en: "electron", vi: "electron" },
      { en: "telescope", vi: "kính viễn vọng" },
      { en: "microscope", vi: "kính hiển vi" },
      { en: "experiment", vi: "thí nghiệm" },
      { en: "hypothesis", vi: "giả thuyết" },
      { en: "analysis", vi: "phân tích" },
      { en: "genetics", vi: "di truyền học" },
      { en: "algorithm", vi: "thuật toán" },
      { en: "radiation", vi: "bức xạ" },
      { en: "thermodynamics", vi: "nhiệt động lực học" },
      { en: "momentum", vi: "động lượng" },
      { en: "inertia", vi: "quán tính" }
    ],
    hard: [
      { en: "quantum", vi: "lượng tử" },
      { en: "relativity", vi: "thuyết tương đối" },
      { en: "nanotechnology", vi: "công nghệ nano" },
      { en: "biotechnology", vi: "công nghệ sinh học" },
      { en: "astrobiology", vi: "sinh học vũ trụ" },
      { en: "neuroscience", vi: "khoa học thần kinh" },
      { en: "chromosome", vi: "nhiễm sắc thể" },
      { en: "photosynthetic", vi: "thuộc quang hợp" },
      { en: "electromagnetism", vi: "điện từ học" },
      { en: "thermodynamic", vi: "nhiệt động học" },
      { en: "epigenetics", vi: "biểu sinh học" },
      { en: "cytology", vi: "tế bào học" },
      { en: "spectroscopy", vi: "quang phổ học" },
      { en: "microbiology", vi: "vi sinh học" },
      { en: "geophysics", vi: "địa vật lý" },
      { en: "astrophysics", vi: "vật lý thiên văn" },
      { en: "bioinformatics", vi: "tin sinh học" },
      { en: "superconductivity", vi: "siêu dẫn" },
      { en: "thermonuclear", vi: "nhiệt hạch" },
      { en: "genomics", vi: "hệ gen học" },
      { en: "cybernetics", vi: "điều khiển học" },
      { en: "crystallography", vi: "kết tinh học" },
      { en: "bioluminescence", vi: "sinh học phát quang" },
      { en: "metallurgy", vi: "luyện kim" },
      { en: "polymerization", vi: "trùng hợp" },
      { en: "biochemistry", vi: "hóa sinh" },
      { en: "enzymatic", vi: "thuộc enzym" },
      { en: "cosmology", vi: "vũ trụ học" },
      { en: "paleoclimatology", vi: "cổ khí hậu học" },
      { en: "geochemistry", vi: "địa hóa học" }
    ]
  },
    adventure: {
    easy: [
      { en: "map", vi: "bản đồ" },
      { en: "camp", vi: "trại" },
      { en: "tent", vi: "lều" },
      { en: "hike", vi: "đi bộ đường dài" },
      { en: "trail", vi: "đường mòn" },
      { en: "compass", vi: "la bàn" },
      { en: "path", vi: "lối đi" },
      { en: "rope", vi: "dây thừng" },
      { en: "boat", vi: "thuyền" },
      { en: "river", vi: "dòng sông" },
      { en: "mountain", vi: "núi" },
      { en: "forest", vi: "rừng" },
      { en: "fire", vi: "lửa trại" },
      { en: "torch", vi: "đuốc" },
      { en: "cave", vi: "hang động" },
      { en: "backpack", vi: "ba lô" },
      { en: "travel", vi: "du lịch" },
      { en: "journey", vi: "hành trình" },
      { en: "climb", vi: "leo núi" },
      { en: "explore", vi: "khám phá" },
      { en: "bridge", vi: "cầu" },
      { en: "bike", vi: "xe đạp" },
      { en: "ride", vi: "cưỡi" },
      { en: "guide", vi: "hướng dẫn viên" },
      { en: "hut", vi: "túp lều" },
      { en: "waterfall", vi: "thác nước" },
      { en: "sunrise", vi: "bình minh" },
      { en: "sunset", vi: "hoàng hôn" },
      { en: "sky", vi: "bầu trời" },
      { en: "star", vi: "ngôi sao" }
    ],
    medium: [
      { en: "expedition", vi: "cuộc thám hiểm" },
      { en: "voyage", vi: "chuyến đi dài" },
      { en: "wilderness", vi: "vùng hoang dã" },
      { en: "rafting", vi: "chèo bè" },
      { en: "trekking", vi: "đi bộ đường dài" },
      { en: "kayaking", vi: "chèo kayak" },
      { en: "safari", vi: "chuyến đi săn" },
      { en: "outback", vi: "vùng xa xôi hẻo lánh" },
      { en: "backpacking", vi: "du lịch ba lô" },
      { en: "campfire", vi: "lửa trại" },
      { en: "summit", vi: "đỉnh núi" },
      { en: "basecamp", vi: "trại gốc" },
      { en: "adrenaline", vi: "cảm giác phấn khích" },
      { en: "wildlife", vi: "động vật hoang dã" },
      { en: "terrain", vi: "địa hình" },
      { en: "shelter", vi: "nơi trú ẩn" },
      { en: "binoculars", vi: "ống nhòm" },
      { en: "campground", vi: "khu cắm trại" },
      { en: "treasure", vi: "kho báu" },
      { en: "canyon", vi: "hẻm núi" },
      { en: "volcano", vi: "núi lửa" },
      { en: "desert", vi: "sa mạc" },
      { en: "jungle", vi: "rừng rậm" },
      { en: "parachute", vi: "dù" },
      { en: "glacier", vi: "sông băng" },
      { en: "gorge", vi: "hẻm vực" },
      { en: "marsh", vi: "đầm lầy" },
      { en: "companion", vi: "đồng hành" },
      { en: "milestone", vi: "cột mốc" },
      { en: "checkpoint", vi: "trạm kiểm soát" }
    ],
    hard: [
      { en: "circumnavigation", vi: "hành trình vòng quanh thế giới" },
      { en: "orienteering", vi: "môn định hướng" },
      { en: "alpinism", vi: "leo núi cao" },
      { en: "spelunking", vi: "thám hiểm hang động" },
      { en: "canyoneering", vi: "leo xuống hẻm núi" },
      { en: "mountaineering", vi: "leo núi" },
      { en: "bivouac", vi: "trại tạm" },
      { en: "overlanding", vi: "hành trình đường bộ dài" },
      { en: "expeditionary", vi: "thuộc về thám hiểm" },
      { en: "transcontinental", vi: "xuyên lục địa" },
      { en: "longitudinal", vi: "theo kinh tuyến" },
      { en: "cartography", vi: "khoa học vẽ bản đồ" },
      { en: "navigation", vi: "điều hướng" },
      { en: "exploratory", vi: "mang tính khám phá" },
      { en: "topography", vi: "địa hình học" },
      { en: "geocaching", vi: "trò tìm kho báu bằng GPS" },
      { en: "wayfinding", vi: "xác định phương hướng" },
      { en: "trekker", vi: "người đi bộ đường dài" },
      { en: "adventurer", vi: "người phiêu lưu" },
      { en: "pathfinder", vi: "người mở đường" },
      { en: "overseas", vi: "hải ngoại" },
      { en: "voyager", vi: "người du hành" },
      { en: "nomadic", vi: "du mục" },
      { en: "survivalist", vi: "người sinh tồn" },
      { en: "expansive", vi: "rộng lớn" },
      { en: "intrepid", vi: "gan dạ" },
      { en: "undaunted", vi: "không nao núng" },
      { en: "perseverance", vi: "kiên trì" },
      { en: "endurance", vi: "sức bền" },
      { en: "resilience", vi: "khả năng phục hồi" }
    ]
  }
};
